
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test-mp?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: lr19971204lr

server:
  port: 8080
mybatis-plus:
  mapper-location: classpath:com/liur/mybatisplus/mapper/impl/*.xml
